# 先读取properties格式的配置文件，后读取yml格式的配置文件。读取到的配置以第一次的为准。
server:
  port: 7776 # 访问端口
  tomcat:
    uri-encoding: utf-8

swagger:
  title: "正式环境swagger"
  desc: "测试prod环境的"
  version: "3.0"


aliyun:
  sms:
    accessKeyId: LTAI4GFpUPL7J9XroGu3FxTu
    accessSecret: cEqroPdDJjl6L3JWxcZKZmwd8SKn2p